### ISSUE TITLE
Heatmaps visualization 

### ISSUE THREAD

**Issue by BioCoderR** [mahmoodlab/CLAM#265]
I have a set of images from the TCGA repository with artefactas(mainly penmarks) on the slides. The issue is that when CLAM toolbox is used for the segmentation it is only identify the penmarks and leaving out the tissue. Is there any way to get the whole tissue segmented with any preprocessors.
Here is the example file when i performed `create_heatmap.py` script for this image file and the `config` file(below) is also attached here. First image is the `heatmap` generated and second one is the `original` segmented image.
How can i get the complete tissue covergae for this type of slides?
![TCGA-02-0001-01C-01-BS1_blockmap](https://github.com/user-attachments/assets/f08c8020-b18c-496f-a2a6-f42cc3fef001)
![TCGA-02-0001-01C-01-BS1_mask](https://github.com/user-attachments/assets/5c56b2db-e3cc-4b64-a8c0-bf4f52fa38fe)
```
exp_arguments:
  # number of classes
  n_classes: 3
  # name tag for saving generated figures and assets
  save_exp_code: HEATMAP_OUTPUT 
  # where to save raw asset files
  raw_save_dir: /mnt/root/heatmaps/heatmap_raw_results
  # where to save final heatmaps
  production_save_dir: /mnt/root/heatmaps/heatmap_production_results
  batch_size: 512
data_arguments: 
  # where is data stored; can be a single str path or a dictionary of key, data_dir mapping
  data_dir: /mnt/root/
  # column name for key in data_dir (if a dict mapping is used)
  data_dir_key: source
  # csv list containing slide_ids (can additionally have seg/patch paramters, class labels, etc.)
  process_list: process_list.csv
  # preset file for segmentation/patching
  preset: /mnt/scripts/presets/tcga_basic.csv
  # file extention for slides
  slide_ext: .svs
  # label dictionary for str: interger mapping (optional)
  label_dict:
    IDHwt: 0
    IDHm-c: 1
    IDHm-nc: 2                        
patching_arguments:
  # arguments for patching
  patch_size: 256
  overlap: 0.5
  patch_level: 0
  custom_downsample: 1
encoder_arguments:
  # arguments for the pretrained encoder model
  model_name: uni_v1 # currently support: resnet50_trunc, uni_v1, conch_v1
  target_img_size: 256 # resize images to this size before feeding to encoder
model_arguments: 
  # arguments for initializing model from checkpoint
  ckpt_path: /mnt/root/task_2_tumor_subtyping_CLAM_100_s1/s_0_checkpoint.pt
  model_type: clam_sb # see utils/eval_utils/
  initiate_fn: initiate_model # see utils/eval_utils/
  model_size: small
  drop_out: 0.25
  embed_dim: 1024
heatmap_arguments:
  # downsample at which to visualize heatmap (-1 refers to downsample closest to 32x downsample)
  vis_level: 1
  # transparency for overlaying heatmap on background (0: background only, 1: foreground only)
  alpha: 0.5
  # whether to use a blank canvas instead of original slide
  blank_canvas: false
  # whether to also save the original H&E image
  save_orig: true
  # file extension for saving heatmap/original image
  save_ext: jpg
  # whether to calculate percentile scores in reference to the set of non-overlapping patches
  use_ref_scores: true
  # whether to use gaussian blur for further smoothing
  blur: true
  # whether to shift the 4 default corner points for checking if a patch is inside a foreground contour
  use_center_shift: true
  # whether to only compute heatmap for ROI specified by x1, x2, y1, y2
  use_roi: false 
  # whether to calculate heatmap with specified overlap (by default, coarse heatmap without overlap is always calculated)
  calc_heatmap: true
  # whether to binarize attention scores
  binarize: false
  # binarization threshold: (0, 1)
  binary_thresh: -1
  # factor for downscaling the heatmap before final dispaly
  custom_downsample: 1
  cmap: jet
sample_arguments:
  samples:
    - name: "topk_high_attention"
      sample: true
      seed: 1
      k: 15 # save top-k patches
      mode: topk
```
